version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www
hooks:
  BeforeInstall:
    - location: dependencies/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: dependencies/after.sh
      timeout: 300
      runas: root
    - location: dependencies/bower.sh
      timeout: 300
      runas: ubuntu
